[2025-02-15T01:27:14.430+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-15T01:27:14.434+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2025-02-15T01:27:14.437+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2024-02-20T00:00:00+00:00 [queued]>
[2025-02-15T01:27:14.437+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-15T01:27:14.445+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2024-02-20 00:00:00+00:00
[2025-02-15T01:27:14.447+0000] {standard_task_runner.py:72} INFO - Started process 182 to run task
[2025-02-15T01:27:14.449+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'scheduled__2024-02-20T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmp9_v1q5bz']
[2025-02-15T01:27:14.450+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask extract_data
[2025-02-15T01:27:14.469+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data scheduled__2024-02-20T00:00:00+00:00 [running]> on host 4360a910c8ec
[2025-02-15T01:27:14.505+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-20T00:00:00+00:00'
[2025-02-15T01:27:14.506+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-15T01:27:14.525+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker
[2025-02-15T01:27:14.530+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-15T01:27:16.786+0000] {docker.py:73} INFO - [0m01:27:16  Running with dbt=1.9.2
[2025-02-15T01:27:16.988+0000] {docker.py:73} INFO - [0m01:27:16  Registered adapter: duckdb=1.9.1
[2025-02-15T01:27:17.039+0000] {docker.py:73} INFO - [0m01:27:17  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-15T01:27:18.094+0000] {docker.py:73} INFO - [0m01:27:18  Found 2 models, 1 seed, 28 data tests, 424 macros
[2025-02-15T01:27:18.095+0000] {docker.py:73} INFO - [0m01:27:18
[2025-02-15T01:27:18.095+0000] {docker.py:73} INFO - [0m01:27:18  Concurrency: 1 threads (target='dev')
[2025-02-15T01:27:18.096+0000] {docker.py:73} INFO - [0m01:27:18
[2025-02-15T01:27:19.634+0000] {docker.py:73} INFO - [0m01:27:19  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-15T01:27:46.098+0000] {docker.py:73} INFO - [0m01:27:46  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 26.46s]
[2025-02-15T01:27:46.137+0000] {docker.py:73} INFO - [0m01:27:46
[2025-02-15T01:27:46.137+0000] {docker.py:73} INFO - [0m01:27:46  Finished running 1 table model in 0 hours 0 minutes and 28.04 seconds (28.04s).
[2025-02-15T01:27:46.221+0000] {docker.py:73} INFO - [0m01:27:46
[2025-02-15T01:27:46.222+0000] {docker.py:73} INFO - [0m01:27:46  [32mCompleted successfully[0m
[2025-02-15T01:27:46.222+0000] {docker.py:73} INFO - [0m01:27:46
[2025-02-15T01:27:46.222+0000] {docker.py:73} INFO - [0m01:27:46  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-15T01:27:46.681+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-15T01:27:46.681+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=scheduled__2024-02-20T00:00:00+00:00, execution_date=20240220T000000, start_date=20250215T012714, end_date=20250215T012746
[2025-02-15T01:27:46.743+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-15T01:27:46.754+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-15T01:27:46.755+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
